-- Groups
INSERT INTO Groups (group_number, headman, course, specialty) VALUES
    ('GROUP-05A', 'Noemi Peddle', 1, 'Engineering'),
    ('GROUP-05B', 'Simone Cartland', 2, 'Physics'),
    ('GROUP-05C', 'Crispin Caddell', 3, 'Informatics'),
    ('GROUP-05D', 'Gustav Beadon', 4, 'Mathematics'),
    ('GROUP-05E', 'Norah Yandell', 5, 'Engineering'),
    ('GROUP-05F', 'Reuben Bristow', 1, 'Mathematics'),
    ('GROUP-05G', 'Deirdre Sorrell', 3, 'Informatics'),
    ('GROUP-05H', 'Glenys Hartwell', 2, 'Engineering'),
    ('GROUP-05I', 'Luciano Clough', 4, 'Physics'),
    ('GROUP-05J', 'Clare Stanley', 3, 'Engineering'),
    ('GROUP-05K', 'Marty Dickens', 2, 'Physics'),
    ('GROUP-05L', 'Freya Phyllis', 5, 'Informatics'),
    ('GROUP-05M', 'Anita Meed', 1, 'Physics'),
    ('GROUP-05N', 'Nina Ralston', 3, 'Mathematics'),
    ('GROUP-05O', 'Ariella Fiske', 4, 'Engineering'),
    ('GROUP-05P', 'Mila Worsley', 2, 'Engineering'),
    ('GROUP-05Q', 'Richard Doveton', 5, 'Physics'),
    ('GROUP-05R', 'Felicitas Horne', 1, 'Mathematics'),
    ('GROUP-05S', 'Oliver Eastgate', 2, 'Informatics'),
    ('GROUP-05T', 'Laurel Giddings', 4, 'Mathematics'),
       ('GROUP-01A', 'Karee Stych', 1, 'Engineering'),
    ('GROUP-01B', 'Aurthur Clausner', 3, 'Physics'),
    ('GROUP-01C', 'Otto Ralph', 5, 'Engineering'),
    ('GROUP-01D', 'Felic Van de Vlies', 2, 'Physics'),
    ('GROUP-01E', 'Abigael Tod', 3, 'Mathematics'),
    ('GROUP-01F', 'Brook Hanhardt', 2, 'Engineering'),
    ('GROUP-01G', 'Leslie Oakwell', 4, 'Mathematics'),
    ('GROUP-01H', 'Celestyn Babber', 4, 'Mathematics'),
    ('GROUP-01I', 'Aileen Ballintyne', 5, 'Mathematics'),
    ('GROUP-02A', 'Cob Colliber', 5, 'Engineering'),
    ('GROUP-02B', 'Gertrudis Yirrell', 5, 'Informatics'),
    ('GROUP-02C', 'Van Lamden', 2, 'Engineering'),
    ('GROUP-02D', 'Dennet Jocelyn', 2, 'Physics'),
    ('GROUP-02E', 'Tania Greenside', 3, 'Physics'),
    ('GROUP-02F', 'Darren Malham', 1, 'Informatics'),
    ('GROUP-02G', 'Carlota Sloper', 3, 'Physics'),
    ('GROUP-02H', 'Arlan Paulmann', 4, 'Engineering'),
    ('GROUP-02I', 'Tatiana Skelding', 3, 'Physics'),
    ('GROUP-02J', 'Chantal Ikringill', 2, 'Informatics'),
    ('GROUP-02K', 'Amalle Morpeth', 1, 'Mathematics'),
    ('GROUP-02L', 'Brigid De Giorgio', 1, 'Engineering'),
    ('GROUP-03A', 'Merry Regitz', 4, 'Engineering'),
    ('GROUP-03B', 'Lucille Curreen', 1, 'Physics'),
    ('GROUP-03C', 'Jannelle Feirn', 2, 'Physics'),
    ('GROUP-03D', 'Isobel Ferrick', 3, 'Engineering'),
    ('GROUP-03E', 'Karl Swenson', 3, 'Informatics'),
    ('GROUP-03F', 'Esme Rustman', 4, 'Engineering'),
    ('GROUP-03G', 'Arnoldo Simony', 5, 'Physics'),
    ('GROUP-03H', 'Cleopatra Covely', 4, 'Mathematics'),
    ('GROUP-03I', 'Carmel Wellard', 4, 'Physics'),
    ('GROUP-03J', 'Augustina Deeny', 5, 'Informatics'),
    ('GROUP-03K', 'Darsie Aberkirder', 4, 'Physics'),
    ('GROUP-03L', 'Shelby Meritt', 4, 'Physics'),
    ('GROUP-03M', 'Constancy Goaley', 4, 'Engineering'),
    ('GROUP-03N', 'Gill Goodredge', 5, 'Mathematics'),
    ('GROUP-03O', 'Andi Eschalotte', 1, 'Mathematics'),
    ('GROUP-03P', 'Ophelia Hamments', 2, 'Engineering'),
    ('GROUP-03Q', 'Noni Eskrick', 5, 'Physics'),
    ('GROUP-03R', 'Glennis Goodbourn', 1, 'Physics'),
    ('GROUP-03S', 'Aymer North', 4, 'Mathematics'),
    ('GROUP-03T', 'Granville Cowie', 2, 'Informatics'),
    ('GROUP-03U', 'Sallie Revely', 4, 'Mathematics'),
    ('GROUP-03V', 'Irvin Milius', 3, 'Informatics'),
    ('GROUP-03W', 'Randa Jindra', 3, 'Mathematics'),
    ('GROUP-03X', 'Davidde Elstone', 3, 'Engineering'),
    ('GROUP-03Y', 'Brnaba Hawkett', 5, 'Informatics'),
    ('GROUP-03Z', 'Les Madelin', 3, 'Physics'),
    ('GROUP-04A', 'Sunny Mouncher', 1, 'Engineering'),
    ('GROUP-04B', 'Sergeant Geddis', 4, 'Mathematics'),
    ('GROUP-04C', 'Augustine Demer', 2, 'Mathematics'),
    ('GROUP-04D', 'Aile Rudeforth', 1, 'Mathematics'),
    ('GROUP-04E', 'Willi Saintsbury', 1, 'Mathematics'),
    ('GROUP-04F', 'Mason Fullegar', 5, 'Engineering'),
    ('GROUP-04G', 'Merola Dabney', 5, 'Physics'),
    ('GROUP-04H', 'Sonni Grief', 5, 'Engineering'),
    ('GROUP-04I', 'Osmund Sirmond', 1, 'Mathematics'),
    ('GROUP-04J', 'Fredek Marlin', 2, 'Informatics'),
    ('GROUP-04K', 'Esther MacRinn', 3, 'Informatics'),
    ('GROUP-04L', 'Aarika Benardette', 4, 'Physics'),
    ('GROUP-04M', 'Field Woolaghan', 1, 'Mathematics'),
    ('GROUP-04N', 'Deane Von Der Empten', 5, 'Physics'),
    ('GROUP-04O', 'Lyndsie Ackeroyd', 4, 'Engineering'),
    ('GROUP-04P', 'Terri Boecke', 5, 'Informatics'),
    ('GROUP-04Q', 'Maridel Aizikovitch', 3, 'Informatics'),
    ('GROUP-04R', 'Akim Maven', 3, 'Mathematics'),
    ('GROUP-04S', 'Jeanie Bridson', 2, 'Physics'),
    ('GROUP-04T', 'Bordie Youens', 2, 'Informatics'),
    ('GROUP-04U', 'Toddy Bougourd', 2, 'Informatics'),
    ('GROUP-04V', 'Phillip Lazenby', 3, 'Engineering'),
    ('GROUP-04W', 'Lowell Noto', 4, 'Informatics'),
    ('GROUP-04X', 'Maybelle Crothers', 5, 'Mathematics'),
    ('GROUP-04Y', 'Kristian Smaile', 1, 'Engineering'),
    ('GROUP-04Z', 'Jen Rosenwasser', 2, 'Informatics');




-- Auditoriums
INSERT INTO Auditoriums (room_number, type, building) VALUES
('100', 'Lecture', 'Building A'),
('101', 'Lecture', 'Building A'),
('102', 'Lecture', 'Building A'),
('103', 'Lecture', 'Building A'),
('104', 'Lecture', 'Building A'),
('105', 'Lecture', 'Building A'),
('106', 'Lecture', 'Building A'),
('107', 'Lecture', 'Building A'),
('108', 'Lecture', 'Building A'),
('109', 'Lecture', 'Building A'),
('110', 'Laboratory', 'Building A'),
('111', 'Laboratory', 'Building A'),
('112', 'Laboratory', 'Building A'),
('113', 'Laboratory', 'Building A'),
('114', 'Laboratory', 'Building A'),
('115', 'Laboratory', 'Building A'),
('116', 'Laboratory', 'Building A'),
('117', 'Laboratory', 'Building A'),
('118', 'Laboratory', 'Building A'),
('119', 'Laboratory', 'Building A'),
('120', 'Seminar', 'Building A'),
('121', 'Seminar', 'Building A'),
('122', 'Seminar', 'Building A'),
('123', 'Seminar', 'Building A'),
('124', 'Seminar', 'Building A'),
('125', 'Seminar', 'Building A'),
('126', 'Seminar', 'Building A'),
('127', 'Seminar', 'Building A'),
('128', 'Seminar', 'Building A'),
('129', 'Seminar', 'Building A'),
('130', 'Lecture', 'Building A'),
('131', 'Lecture', 'Building A'),
('132', 'Lecture', 'Building A'),
('133', 'Lecture', 'Building A'),
('134', 'Lecture', 'Building A'),
('135', 'Lecture', 'Building A'),
('136', 'Lecture', 'Building A'),
('137', 'Lecture', 'Building A'),
('138', 'Lecture', 'Building A'),
('139', 'Lecture', 'Building A'),
('140', 'Laboratory', 'Building A'),
('141', 'Laboratory', 'Building A'),
('142', 'Laboratory', 'Building A'),
('143', 'Laboratory', 'Building A'),
('144', 'Laboratory', 'Building A'),
('145', 'Laboratory', 'Building A'),
('146', 'Laboratory', 'Building A'),
('147', 'Laboratory', 'Building A'),
('148', 'Laboratory', 'Building A'),
('149', 'Laboratory', 'Building A'),
('150', 'Seminar', 'Building A'),
('151', 'Seminar', 'Building A'),
('152', 'Seminar', 'Building A'),
('153', 'Seminar', 'Building A'),
('154', 'Seminar', 'Building A'),
('155', 'Seminar', 'Building A'),
('156', 'Seminar', 'Building A'),
('157', 'Seminar', 'Building A'),
('158', 'Seminar', 'Building A'),
('159', 'Seminar', 'Building A'),
('200', 'Lecture', 'Building B'),
('201', 'Lecture', 'Building B'),
('202', 'Lecture', 'Building B'),
('203', 'Lecture', 'Building B'),
('204', 'Lecture', 'Building B'),
('205', 'Lecture', 'Building B'),
('206', 'Lecture', 'Building B'),
('207', 'Lecture', 'Building B'),
('208', 'Lecture', 'Building B'),
('209', 'Lecture', 'Building B'),
('210', 'Laboratory', 'Building B'),
('211', 'Laboratory', 'Building B'),
('212', 'Laboratory', 'Building B'),
('213', 'Laboratory', 'Building B'),
('214', 'Laboratory', 'Building B'),
('215', 'Laboratory', 'Building B'),
('216', 'Laboratory', 'Building B'),
('217', 'Laboratory', 'Building B'),
('218', 'Laboratory', 'Building B'),
('219', 'Laboratory', 'Building B'),
('220', 'Seminar', 'Building B'),
('221', 'Seminar', 'Building B'),
('222', 'Seminar', 'Building B'),
('223', 'Seminar', 'Building B'),
('224', 'Seminar', 'Building B'),
('225', 'Seminar', 'Building B'),
('226', 'Seminar', 'Building B'),
('227', 'Seminar', 'Building B'),
('228', 'Seminar', 'Building B'),
('229', 'Seminar', 'Building B'),
('230', 'Lecture', 'Building B'),
('231', 'Lecture', 'Building B'),
('232', 'Lecture', 'Building B'),
('233', 'Lecture', 'Building B'),
('234', 'Lecture', 'Building B'),
('235', 'Lecture', 'Building B'),
('236', 'Lecture', 'Building B'),
('237', 'Lecture', 'Building B'),
('238', 'Lecture', 'Building B'),
('239', 'Lecture', 'Building B'),
('240', 'Laboratory', 'Building B'),
('241', 'Laboratory', 'Building B'),
('242', 'Laboratory', 'Building B'),
('243', 'Laboratory', 'Building B'),
('244', 'Laboratory', 'Building B'),
('245', 'Laboratory', 'Building B'),
('246', 'Laboratory', 'Building B'),
('247', 'Laboratory', 'Building B'),
('248', 'Laboratory', 'Building B'),
('249', 'Laboratory', 'Building B'),
('250', 'Seminar', 'Building B'),
('251', 'Seminar', 'Building B'),
('252', 'Seminar', 'Building B'),
('253', 'Seminar', 'Building B'),
('254', 'Seminar', 'Building B'),
('255', 'Seminar', 'Building B'),
('256', 'Seminar', 'Building B'),
('257', 'Seminar', 'Building B'),
('258', 'Seminar', 'Building B'),
('259', 'Seminar', 'Building B'),
('300', 'Lecture', 'Building B');


-- Teachers
INSERT INTO Teachers (full_name, department, position, academic_degree, teaching_types) VALUES
('Sidorov A.A.', 'Mathematics', 'Associate Professor', 'PhD', 'Lecture, Practice'),
('Kozlov V.V.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Petrov P.P.', 'Physics', 'Lecturer', 'PhD', 'Lecture, Practice'),
('Ivanov I.I.', 'Chemistry', 'Associate Professor', 'PhD', 'Lecture'),
('Zaytsev M.M.', 'Biology', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Karpov D.D.', 'Mathematics', 'Assistant Professor', 'Master', 'Lecture'),
('Fedorov N.N.', 'Informatics', 'Associate Professor', 'PhD', 'Lecture, Practice'),
('Baranov O.O.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Gusev V.V.', 'Chemistry', 'Lecturer', 'PhD', 'Lecture, Practice'),
('Lebedev E.E.', 'Physics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Vasilenko A.A.', 'Informatics', 'Lecturer', 'Master', 'Lecture'),
('Mikhailov P.P.', 'Biology', 'Assistant Professor', 'PhD', 'Lecture'),
('Kuznetsov A.A.', 'Mathematics', 'Lecturer', 'PhD', 'Lecture'),
('Poltavsky I.I.', 'Chemistry', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Zelenin Y.Y.', 'Informatics', 'Associate Professor', 'PhD', 'Lecture, Practice'),
('Nikolayev S.S.', 'Physics', 'Lecturer', 'PhD', 'Lecture'),
('Alekseev A.A.', 'Mathematics', 'Assistant Professor', 'PhD', 'Lecture'),
('Ozerov D.D.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Sergeev P.P.', 'Chemistry', 'Associate Professor', 'PhD', 'Lecture'),
('Kuzmin M.M.', 'Biology', 'Assistant Professor', 'Master', 'Lecture'),
('Zharov S.S.', 'Physics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Volkov I.I.', 'Informatics', 'Assistant Professor', 'PhD', 'Lecture, Practice'),
('Andreev Y.Y.', 'Mathematics', 'Lecturer', 'PhD', 'Lecture'),
('Makarov N.N.', 'Biology', 'Associate Professor', 'PhD', 'Lecture'),
('Shirokov E.E.', 'Chemistry', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Bondarenko A.A.', 'Physics', 'Associate Professor', 'PhD', 'Lecture'),
('Rogov P.P.', 'Informatics', 'Lecturer', 'Master', 'Lecture'),
('Klimov V.V.', 'Biology', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Orlov A.A.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Frolov P.P.', 'Chemistry', 'Lecturer', 'Master', 'Lecture'),
('Kozachenko I.I.', 'Physics', 'Associate Professor', 'PhD', 'Lecture'),
('Tikhonov D.D.', 'Informatics', 'Lecturer', 'PhD', 'Lecture'),
('Romanov A.A.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Sokolov P.P.', 'Chemistry', 'Lecturer', 'PhD', 'Lecture'),
('Shvidko Y.Y.', 'Biology', 'Associate Professor', 'PhD', 'Lecture'),
('Grebnev S.S.', 'Physics', 'Assistant Professor', 'Master', 'Lecture'),
('Kireev A.A.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Popov P.P.', 'Mathematics', 'Lecturer', 'Master', 'Lecture'),
('Chistyakov M.M.', 'Chemistry', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Kondratov D.D.', 'Physics', 'Assistant Professor', 'PhD', 'Lecture, Practice'),
('Gorban Y.Y.', 'Informatics', 'Assistant Professor', 'PhD', 'Lecture'),
('Novikov A.A.', 'Mathematics', 'Associate Professor', 'PhD', 'Lecture'),
('Pavlov P.P.', 'Biology', 'Lecturer', 'Master', 'Lecture'),
('Chernov A.A.', 'Chemistry', 'Associate Professor', 'PhD', 'Lecture'),
('Vasiliev I.I.', 'Physics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Karpova M.M.', 'Informatics', 'Lecturer', 'Master', 'Lecture'),
('Trofimov P.P.', 'Mathematics', 'Assistant Professor', 'PhD', 'Lecture'),
('Peshkov S.S.', 'Chemistry', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Zaharov A.A.', 'Physics', 'Lecturer', 'Master', 'Lecture'),
('Vinnikov P.P.', 'Informatics', 'Associate Professor', 'PhD', 'Lecture'),
('Melikhov S.S.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Akimov A.A.', 'Biology', 'Lecturer', 'PhD', 'Lecture'),
('Golovnev D.D.', 'Informatics', 'Assistant Professor', 'PhD', 'Lecture'),
('Chernyshov P.P.', 'Chemistry', 'Associate Professor', 'PhD', 'Lecture'),
('Lazarev V.V.', 'Physics', 'Assistant Professor', 'Master', 'Lecture'),
('Kovalenko M.M.', 'Mathematics', 'Lecturer', 'PhD', 'Lecture'),
('Fedotov D.D.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Dmitriev A.A.', 'Chemistry', 'Assistant Professor', 'Master', 'Lecture'),
('Sinitsa Y.Y.', 'Physics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Mikheev A.A.', 'Mathematics', 'Assistant Professor', 'PhD', 'Lecture'),
('Dubrovsky P.P.', 'Informatics', 'Lecturer', 'Master', 'Lecture'),
('Nikitin S.S.', 'Chemistry', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Ilyin P.P.', 'Biology', 'Associate Professor', 'PhD', 'Lecture'),
('Zolotukhin A.A.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture, Practice'),
('Gavrilov P.P.', 'Physics', 'Assistant Professor', 'PhD', 'Lecture'),
('Belyakov S.S.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Krasnov Y.Y.', 'Mathematics', 'Lecturer', 'Master', 'Lecture'),
('Petrakov A.A.', 'Chemistry', 'Assistant Professor', 'PhD', 'Lecture'),
('Grishin M.M.', 'Informatics', 'Associate Professor', 'PhD', 'Lecture'),
('Zaitsev D.D.', 'Biology', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Krasikova A.A.', 'Physics', 'Lecturer', 'Master', 'Lecture'),
('Ostapenko A.A.', 'Mathematics', 'Associate Professor', 'PhD', 'Lecture'),
('Semenov P.P.', 'Informatics', 'Lecturer', 'Master', 'Lecture'),
('Baranov D.D.', 'Chemistry', 'Lecturer', 'PhD', 'Lecture'),
('Rozov V.V.', 'Physics', 'Associate Professor', 'PhD', 'Lecture'),
('Kovtun Y.Y.', 'Biology', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Markov A.A.', 'Mathematics', 'Assistant Professor', 'PhD', 'Lecture'),
('Tsarov P.P.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Gusev M.M.', 'Physics', 'Lecturer', 'Master', 'Lecture'),
('Baranov S.S.', 'Chemistry', 'Associate Professor', 'PhD', 'Lecture'),
('Kozhevnikov P.P.', 'Informatics', 'Assistant Professor', 'Master', 'Lecture'),
('Zhukov A.A.', 'Mathematics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Pavlova M.M.', 'Chemistry', 'Lecturer', 'PhD', 'Lecture'),
('Yaroslavskiy D.D.', 'Physics', 'Associate Professor', 'PhD', 'Lecture'),
('Kapustin P.P.', 'Informatics', 'Associate Professor', 'PhD', 'Lecture, Practice'),
('Kulikov A.A.', 'Biology', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Zaharov S.S.', 'Mathematics', 'Lecturer', 'Master', 'Lecture'),
('Striganov A.A.', 'Chemistry', 'Assistant Professor', 'Master', 'Lecture'),
('Chernikov P.P.', 'Physics', 'Assistant Professor', 'PhD', 'Lecture'),
('Frolova M.M.', 'Informatics', 'Professor', 'Doctor of Sciences', 'Lecture'),
('Vasiliev D.D.', 'Mathematics', 'Lecturer', 'Master', 'Lecture'),
('Smirnov S.S.', 'Biology', 'Associate Professor', 'PhD', 'Lecture');

-- Subjects
-- Генерация 100 уникальных записей для таблицы Subjects
INSERT INTO Subjects (name) VALUES
('Calculus'),
('Physics'),
('Chemistry'),
('Biology'),
('History'),
('Geography'),
('Literature'),
('Philosophy'),
('Economics'),
('Psychology'),
('Sociology'),
('Political Science'),
('Law'),
('Environmental Science'),
('Anthropology'),
('Astronomy'),
('Astronomical Observations'),
('Engineering Mathematics'),
('Applied Mathematics'),
('Discrete Mathematics'),
('Linear Algebra'),
('Statistics'),
('Data Science'),
('Machine Learning'),
('Artificial Intelligence'),
('Computer Science Fundamentals'),
('Object-Oriented Programming'),
('Web Development'),
('Mobile Development'),
('Database Systems'),
('Operating Systems'),
('Computer Networks'),
('Cybersecurity'),
('Cloud Computing'),
('Software Engineering'),
('Game Development'),
('Computer Graphics'),
('Data Structures'),
('Algorithms'),
('Compiler Design'),
('Distributed Systems'),
('Embedded Systems'),
('IoT (Internet of Things)'),
('Blockchain Technology'),
('Virtual Reality'),
('Augmented Reality'),
('Computer Vision'),
('Natural Language Processing'),
('Digital Signal Processing'),
('Quantum Computing'),
('Business Administration'),
('Financial Management'),
('Marketing'),
('Human Resources Management'),
('Project Management'),
('Leadership Skills'),
('Business Ethics'),
('Accounting'),
('International Relations'),
('Public Relations'),
('Media Studies'),
('Digital Marketing'),
('Web Analytics'),
('Design Thinking'),
('Creative Writing'),
('Poetry'),
('Journalism'),
('Script Writing'),
('Graphic Design'),
('User Experience Design'),
('User Interface Design'),
('Product Design'),
('Photography'),
('Film Studies'),
('Acting Techniques'),
('Music Theory'),
('Classical Music'),
('Jazz Music'),
('Opera'),
('Choir Performance'),
('Music Composition'),
('Art History'),
('Painting Techniques'),
('Sculpture'),
('Ceramics'),
('Drawing Techniques'),
('Fashion Design'),
('Interior Design'),
('Architecture'),
('Civil Engineering'),
('Mechanical Engineering'),
('Electrical Engineering'),
('Chemical Engineering'),
('Aerospace Engineering'),
('Biomedical Engineering'),
('Environmental Engineering'),
('Materials Science'),
('Nanotechnology'),
('Renewable Energy'),
('Sustainable Development'),
('Urban Planning'),
('Geology'),
('Geophysics'),
('Meteorology'),
('Hydrology'),
('Marine Biology'),
('Animal Behavior'),
('Botany'),
('Ecology'),
('Zoology'),
('Genetics'),
('Evolutionary Biology'),
('Microbiology'),
('Immunology'),
('Virology'),
('Pharmacology'),
('Anatomy'),
('Physiology'),
('Pathology'),
('Neuroscience'),
('Public Health'),
('Health Administration'),
('Epidemiology'),
('Forensic Science'),
('Veterinary Science'),
('Pharmaceutical Sciences');


ALTER TABLE Schedule
DROP CONSTRAINT CK__Schedule__day_of__4222D4EF;


-- Schedule
INSERT INTO Schedule (day_of_week, pair_number, teacher_id, group_id, subject_id, auditorium_id) VALUES
('Monday', 1, 1, 1, 61, 1),
('Monday', 2, 2, 2, 78, 2),
('Monday', 3, 3, 8, 97, 3),
('Monday', 4, 4, 9, 1, 4),
('Monday', 5, 5, 10, 42, 5),
('Tuesday', 1, 6, 11, 120, 6),
('Tuesday', 2, 7, 12, 110, 7),
('Tuesday', 3, 8, 13, 18, 8),
('Tuesday', 4, 9, 14, 22, 9),
('Tuesday', 5, 10, 15, 92, 10),
('Wednesday', 1, 11, 16, 85, 11),
('Wednesday', 2, 12, 17, 28, 12),
('Wednesday', 3, 13, 18, 20, 13),
('Wednesday', 4, 14, 19, 19, 14),
('Wednesday', 5, 15, 20, 49, 15),
('Thursday', 1, 16, 21, 7, 16),
('Thursday', 2, 17, 22, 98, 17),
('Thursday', 3, 18, 23, 47, 18),
('Thursday', 4, 19, 24, 111, 19),
('Thursday', 5, 20, 25, 54, 20),
('Friday', 1, 21, 26, 60, 21),
('Friday', 2, 22, 27, 4, 22),
('Friday', 3, 23, 28, 88, 23),
('Friday', 4, 24, 29, 96, 24),
('Friday', 5, 25, 30, 6, 25),
('Monday', 1, 26, 31, 83, 26),
('Monday', 2, 27, 32, 93, 27),
('Monday', 3, 28, 33, 80, 28),
('Monday', 4, 29, 34, 37, 29),
('Monday', 5, 30, 35, 43, 30),
('Tuesday', 1, 31, 36, 40, 31),
('Tuesday', 2, 32, 37, 35, 32),
('Tuesday', 3, 33, 38, 29, 33),
('Tuesday', 4, 34, 39, 50, 34),
('Tuesday', 5, 35, 40, 68, 35),
('Wednesday', 1, 36, 41, 36, 36),
('Wednesday', 2, 37, 42, 26, 37),
('Wednesday', 3, 38, 43, 41, 38),
('Wednesday', 4, 39, 44, 33, 39),
('Wednesday', 5, 40, 45, 67, 40),
('Thursday', 1, 41, 46, 65, 41),
('Thursday', 2, 42, 47, 52, 42),
('Thursday', 3, 43, 48, 23, 43),
('Thursday', 4, 44, 49, 44, 44),
('Thursday', 5, 45, 50, 89, 45),
('Friday', 1, 46, 51, 112, 46),
('Friday', 2, 47, 52, 12, 47),
('Friday', 3, 48, 53, 95, 48),
('Friday', 4, 49, 54, 45, 49),
('Friday', 5, 50, 55, 21, 50),
('Monday', 1, 51, 56, 99, 51),
('Monday', 2, 52, 57, 17, 52),
('Monday', 3, 53, 58, 126, 53),
('Monday', 4, 54, 59, 115, 54),
('Monday', 5, 55, 60, 90, 55),
('Tuesday', 1, 56, 61, 77, 56),
('Tuesday', 2, 57, 62, 55, 57),
('Tuesday', 3, 58, 63, 127, 58),
('Tuesday', 4, 59, 64, 39, 59),
('Tuesday', 5, 60, 65, 114, 60);


